# Generated by Django 4.2.13 on 2024-06-04 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tweets", "0003_alter_like_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="like",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="like",
            constraint=models.UniqueConstraint(fields=("tweet", "user"), name="unique_like"),
        ),
    ]
